### ISSUE TITLE
Mapping gRPC code to HTTP status code

### ISSUE THREAD

**Issue by dzungbui291** [Kong/kong-plugin-grpc-gateway#24]
Hi all,
I am using grpc-gateway to transport REST API to gRPC microservices. But when gRPC response to Kong, the status code don't convert, the status code in HTTP always return 200.
Please help me convert this status code.

Thanks!!!

**Comment by fffonion** [comment]
Hi @dzungbui291 , per my understanding the specification doesn't say which field in the gRPC response should be mapped
to HTTP staus code (https://github.com/googleapis/googleapis/blob/master/google/api/http.proto).
Can you describe more about your use case? What do you expect to be the status code be related to?

**Comment by dzungbui291** [comment]
Thank @fffonion ,
In my case, when gPRC service return an error, how to grpc-gateway convert to HTTP error code.
Example: gRPC return NOT_FOUND error, but the status code in HTTP response is 200 OK (expect status: 400 ).
the gRPC-Gateway is auto convert this status code? or any configs for this issue?

Thanks so much!!!

**Comment by fffonion** [comment]
I see, we can map `grpc-status` headers back to the http status code. I will open a PR.

**Comment by dzungbui291** [comment]
Hi @fffonion ,
I will check again after this pull request merged.

Thanks so much!!
